// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var Factory, Helpers, LineUp, Promise, helpers, lineup, _;

  _ = require("lodash");

  Promise = require("bluebird");

  Helpers = require("../../util/Helpers");

  helpers = new Helpers();

  LineUp = require("lineup");

  lineup = new LineUp();


  /**
     * Class to fetch and run hooks registered for generate:factory process/command
     * @class Factory
     * @constructor
   */

  Factory = (function() {
    function Factory() {}


    /**
       * @method run
       * @param args {Object} accept arguments passed with generate:factory command
       * @description Entry point to generate:factory command and run all registered hooks
     */

    Factory.prototype.run = function(args) {
      helpers.sortModules("generate:factory").then(function(hooks_to_proccess) {
        if (_.size(hooks_to_proccess) > 0) {
          helpers.getConfig(function(err, ngconfig) {
            if (err) {
              lineup.log.error(err);
              process.exit(1);
            } else {
              helpers.run("generate:factory", hooks_to_proccess, ngconfig, args);
            }
          });
        } else {
          lineup.log.warn("0 hooks configured for this proccess");
          process.exit(1);
        }
      });
    };

    return Factory;

  })();

  module.exports = Factory;

}).call(this);
