// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var Helpers, Initializer, LineUp, Promise, helpers, lineup, _;

  _ = require("lodash");

  Promise = require("bluebird");

  Helpers = require("../../util/Helpers");

  helpers = new Helpers();

  LineUp = require("lineup");

  lineup = new LineUp();


  /**
     * Class to fetch and run hooks registered for generate:initializer process/command
     * @class Initializer
     * @constructor
   */

  Initializer = (function() {
    function Initializer() {}


    /**
       * @method run
       * @param args {Object} accept arguments passed with generate:initializer command
       * @description Entry point to generate:initializer command and run all registered hooks
     */

    Initializer.prototype.run = function(args) {
      helpers.sortModules("generate:initializer").then(function(hooks_to_proccess) {
        if (_.size(hooks_to_proccess) > 0) {
          helpers.getConfig(function(err, ngconfig) {
            if (err) {
              lineup.log.error(err);
              process.exit(1);
            } else {
              helpers.run("generate:initializer", hooks_to_proccess, ngconfig, args);
            }
          });
        } else {
          lineup.log.warn("0 hooks configured for this proccess");
          process.exit(1);
        }
      });
    };

    return Initializer;

  })();

  module.exports = Initializer;

}).call(this);
