// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var Initializer, LineUp, Promise, Runner, lineup, runner, _;

  _ = require("lodash");

  Promise = require("bluebird");

  Runner = require("../../util/Runner");

  runner = new Runner();

  LineUp = require("lineup");

  lineup = new LineUp();


  /**
     * Class to fetch and run hooks registered for generate:initializer process/command
     * @class Initializer
     * @constructor
   */

  Initializer = (function() {
    function Initializer() {}


    /**
       * @method run
       * @param args {Object} accept arguments passed with generate:initializer command
       * @description Entry point to generate:initializer command and run all registered hooks
     */

    Initializer.prototype.run = function(args) {
      runner.sortModules("generate:initializer").then(function(hooks_to_proccess) {
        if (_.size(hooks_to_proccess) > 0) {
          runner.getConfig(function(err, ngconfig) {
            if (err) {
              runner.trace(err);
              process.exit(1);
            } else {
              runner.run("generate:initializer", hooks_to_proccess, ngconfig, args);
            }
          });
        } else {
          runner.notify("warn", "0 hooks configured for this proccess");
          process.exit(1);
        }
      })["catch"](function(err) {
        runner.trace(err);
        process.exit(1);
      });
    };

    return Initializer;

  })();

  module.exports = Initializer;

}).call(this);
