// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var LineUp, Promise, Runner, Service, lineup, runner, _;

  _ = require("lodash");

  Promise = require("bluebird");

  Runner = require("../../util/Runner");

  runner = new Runner();

  LineUp = require("lineup");

  lineup = new LineUp();


  /**
     * Class to fetch and run hooks registered for generate:service process/command
     * @class Service
     * @constructor
   */

  Service = (function() {
    function Service() {}


    /**
       * @method run
       * @param args {Object} accept arguments passed with generate:service command
       * @description Entry point to generate:service command and run all registered hooks
     */

    Service.prototype.run = function(args) {
      runner.sortModules("generate:service").then(function(hooks_to_proccess) {
        if (_.size(hooks_to_proccess) > 0) {
          runner.getConfig(function(err, ngconfig) {
            if (err) {
              lineup.log.error(err);
              process.exit(1);
            } else {
              runner.run("generate:service", hooks_to_proccess, ngconfig, args);
            }
          });
        } else {
          runner.notify("warn", "0 hooks configured for this proccess");
          process.exit(1);
        }
      })["catch"](function(err) {
        runner.trace(err);
        process.exit(1);
      });
    };

    return Service;

  })();

  module.exports = Service;

}).call(this);
