// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var Promise, Runner, Sync, Tasks, runner, tasks, _;

  _ = require("lodash");

  Promise = require("bluebird");

  Runner = require("../util/Runner");

  runner = new Runner();

  Tasks = require("../bundled-commands/Tasks");

  tasks = new Tasks();


  /**
     * Class to sync local and bundled hooks
     * @class Sync
     * @constructor
   */

  Sync = (function() {
    function Sync() {}


    /**
       * @method run
       * @param args {Object} accept arguments passed with sync command
       * @description Entry point to sync command
     */

    Sync.prototype.run = function(args, watch) {
      runner.sortModules("build").then(function(hooks_to_proccess) {
        runner.getConfig(function(err, ngconfig) {
          if (err) {
            runner.trace(err);
          } else {
            runner.run("generate:controller", hooks_to_proccess, ngconfig, args, function() {
              return tasks.parse().then(function() {
                return tasks.runTasks();
              }).then(function() {
                if (watch) {
                  tasks.checkAndStartServer();
                  tasks.registerWatchers();
                  return;
                }
              })["catch"](function(err) {
                runner.trace(err);
              });
            });
          }
        });
      });
    };

    return Sync;

  })();

  module.exports = Sync;

}).call(this);
