// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var ControllerGenerator, DirectiveGenerator, FactoryGenerator, FilterGenerator, Generate, Helpers, InitializerGenerator, ServiceGenerator, helpers;

  ControllerGenerator = require("../commands/generate/controller");

  FilterGenerator = require("../commands/generate/filter");

  DirectiveGenerator = require("../commands/generate/directive");

  ServiceGenerator = require("../commands/generate/service");

  FactoryGenerator = require("../commands/generate/factory");

  InitializerGenerator = require("../commands/generate/initializer");

  Helpers = require("../util/Helpers");

  helpers = new Helpers();

  Generate = (function() {
    function Generate() {}

    Generate.prototype.run = function(parsed) {
      var cg, dg, fcg, fg, generator, identifier, ig, sg;
      generator = parsed.generator;
      if (generator.length > 1) {
        identifier = generator[0];
        switch (identifier) {
          case "controller":
            cg = new ControllerGenerator();
            cg.run(parsed);
            break;
          case "filter":
            fg = new FilterGenerator();
            fg.run(parsed);
            break;
          case "factory":
            fcg = new FactoryGenerator();
            fcg.run(parsed);
            break;
          case "service":
            sg = new ServiceGenerator();
            sg.run(parsed);
            break;
          case "initializer":
            ig = new InitializerGenerator();
            ig.run(parsed);
            break;
          case "directive":
            dg = new DirectiveGenerator();
            dg.run(parsed);
            break;
          default:
            helpers.notify("error", "Not a valid generator");
        }
      } else {
        helpers.notify("error", "Not a valid generator");
      }
    };

    return Generate;

  })();

  module.exports = Generate;

}).call(this);
