// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var Helpers, Hook, LineUp, Promise, helpers, lineup, _;

  _ = require("lodash");

  Promise = require("bluebird");

  Helpers = require("../util/Helpers");

  helpers = new Helpers();

  LineUp = require("lineup");

  lineup = new LineUp();


  /**
     * Class to run anonymous hooks from anywhere and for any purpopse
     * @class Hook
     * @constructor
   */

  Hook = (function() {
    function Hook() {}


    /**
       * @method run
       * @param args {Object} accept arguments passed with hook command
       * @description Entry point to hook command and run all registered hooks
     */

    Hook.prototype.run = function(args) {
      helpers.getConfig(function(err, ngconfig) {
        if (err) {
          helpers.trace(err);
        } else {
          helpers.run("hook", [args.command], ngconfig, args);
        }
      });
    };

    return Hook;

  })();

  module.exports = Hook;

}).call(this);
